-- noinspection SqlNoDataSourceInspectionForFile

-- create infections table
CREATE TABLE IF NOT EXISTS indicateurs_sip.infections (
    annee VARCHAR,
    indicateur VARCHAR,
    INDICATEUR_P1 DECIMAL,
    INDICATEUR_P2 DECIMAL,
    INDICATEUR_P3 DECIMAL,
    INDICATEUR_P4 DECIMAL,
    INDICATEUR_P5 DECIMAL,
    INDICATEUR_P6 DECIMAL,
    INDICATEUR_P7 DECIMAL,
    INDICATEUR_P8 DECIMAL,
    INDICATEUR_P9 DECIMAL,
    INDICATEUR_P10 DECIMAL,
    INDICATEUR_P11 DECIMAL,
    INDICATEUR_P12 DECIMAL,
    INDICATEUR_P13 DECIMAL,
    INDICATEUR_TOTAL DECIMAL,
    INDICATEUR_TOTALANNEEPRECEDENTE INT,
    denominateur VARCHAR
);