-- noinspection SqlNoDataSourceInspectionForFile

-- create infections table
CREATE TABLE IF NOT EXISTS indicateurs_sip.infections (
    annee VARCHAR,
    indicateur VARCHAR,
    INDICATEUR_P1 DOUBLE,
    INDICATEUR_P2 DOUBLE,
    INDICATEUR_P3 DOUBLE,
    INDICATEUR_P4 DOUBLE,
    INDICATEUR_P5 DOUBLE,
    INDICATEUR_P6 DOUBLE,
    INDICATEUR_P7 DOUBLE,
    INDICATEUR_P8 DOUBLE,
    INDICATEUR_P9 DOUBLE,
    INDICATEUR_P10 DOUBLE,
    INDICATEUR_P11 DOUBLE,
    INDICATEUR_P12 DOUBLE,
    INDICATEUR_P13 DOUBLE,
    INDICATEUR_TOTAL DOUBLE,
    INDICATEUR_TOTALANNEEPRECEDENTE INT,
    denominateur VARCHAR
);