-- noinspection SqlNoDataSourceInspectionForFile

-- create toutes_les_infections  table

CREATE TABLE IF NOT EXISTS indicateurs_sip.toutes_les_infections (
   N0 Int,
   INDICATEUR_ESTCALCULE BOOLEAN,
   INDICATEUR_ANNEE VARCHAR,
   INDICATEUR_UNITE Int,
   NOM_UNITÉ VARCHAR,
   INDICATEUR_NOM Int,
   Calcul_NomIndicateur VARCHAR,
   INDICATEUR_DENOMINATEUR Int,
   LISTDENOMINATEUR_NOM VARCHAR,
   INDICATEUR_P1 Int,
   INDICATEUR_P2 Int,
   INDICATEUR_P3 Int,
   INDICATEUR_P4 Int,
   INDICATEUR_P5 Int,
   INDICATEUR_P6 Int,
   INDICATEUR_P7 Int,
   INDICATEUR_P8 Int,
   INDICATEUR_P9 Int,
   INDICATEUR_P10 Int,
   INDICATEUR_P11 Int,
   INDICATEUR_P12 Int,
   INDICATEUR_P13 Int,
   INDICATEUR_TOTAL Int,
   INDICATEUR_TOTALANNEEPRECEDENTE Int,
   INDICATEUR_CIBLE Int,
   Calcul_ValeurCoefficient Int,
   Calcul_Denominateur Int,
   Calcul_Cible DECIMAL,
   LISTDENOMINATEUR_ANNEE VARCHAR
);