apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  generateName: ingestion-job-
  namespace: ingestion
spec:
  type: Scala
  mode: cluster
  image: ferlabcrsj/spark-operator:3.0.0
  imagePullPolicy: Always
  deps:
    repositories:
      - https://repos.spark-packages.org
    packages:
      - io.delta:delta-core_2.12:0.8.0
      - org.postgresql:postgresql:42.2.23
      - com.microsoft.azure:spark-mssql-connector_2.12:1.1.0
      - com.microsoft.aad:adal4j:0.0.2
      - com.microsoft.sqlserver:mssql-jdbc:8.4.1.jre8
  mainClass: bio.ferlab.ui.etl.red.raw.ImportTables
  mainApplicationFile: "s3a://spark-prd/jars/unic-etl-3.0.0.jar"
  arguments:
    - "config/prod.conf"
    - "{{ dag_run.conf.get('destination', 'raw_eclinibase_v_identification') }}"
    - "{{ dag_run.conf.get('run_type', 'first_load') }}"
  sparkVersion: "3.0.0"
  sparkConf:
    spark.sql.legacy.timeParserPolicy: "CORRECTED"
    spark.sql.legacy.parquet.datetimeRebaseModeInWrite: "CORRECTED"
    spark.hadoop.fs.s3a.endpoint: "https://minio-unic.infojutras.com"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.hadoop.fs.s3a.aws.credentials.provider: "com.amazonaws.auth.EnvironmentVariableCredentialsProvider"
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "true"
    extraJavaOptions: "-Dcom.amazonaws.services.s3.enableV4=true"
    spark.driver.extraJavaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp"
  restartPolicy:
    type: Never
  driver:
    cores: 4
    memory: "28G"
    labels:
      version: 3.0.0
    serviceAccount: spark
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: spark-ingestion-minio
        key: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        name: spark-ingestion-minio
        key: AWS_SECRET_ACCESS_KEY
      ICCA_DB_USERNAME:
        name: spark-ingestion-icca-db
        key: ICCA_DB_USERNAME
      ICCA_DB_PASSWORD:
        name: spark-ingestion-icca-db
        key: ICCA_DB_PASSWORD
      INTEGRATION_DB_USERNAME:
        name: spark-ingestion-integration-db
        key: INTEGRATION_DB_USERNAME
      INTEGRATION_DB_PASSWORD:
        name: spark-ingestion-integration-db
        key: INTEGRATION_DB_PASSWORD

  executor:
    cores: 4
    instances: 2
    memory: "28G"
    labels:
      version: 3.0.0
    envSecretKeyRefs:
      AWS_ACCESS_KEY_ID:
        name: spark-ingestion-minio
        key: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        name: spark-ingestion-minio
        key: AWS_SECRET_ACCESS_KEY
      ICCA_DB_USERNAME:
        name: spark-ingestion-icca-db
        key: ICCA_DB_USERNAME
      ICCA_DB_PASSWORD:
        name: spark-ingestion-icca-db
        key: ICCA_DB_PASSWORD
      INTEGRATION_DB_USERNAME:
        name: spark-ingestion-integration-db
        key: INTEGRATION_DB_USERNAME
      INTEGRATION_DB_PASSWORD:
        name: spark-ingestion-integration-db
        key: INTEGRATION_DB_PASSWORD