name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - run: |
         pip install -r requirements.txt
         pip install pylint
         pip install pylint-airflow
         pylint --load-plugins=pylint_airflow --fail-under=9.0 */**.py


