name: Python CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Install dependencies
        run: |
         pip install "apache-airflow==2.11.2" --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.11.2/constraints-3.12.txt
         pip install -r requirements.txt
      - name: Lint
        run: pylint --fail-under=10.0 $(git ls-files '*.py')
      - name: Test
        run: pytest


